python ./run.py --model "monai_swinunet" \
                --version "v7" \
                --save_path "/mnt/HDD/chest-seg_models" \
                --cuda "0"\
                --ts_batch_size 128\
                --vs_batch_size 64\
                --epochs 2000\
                --loss "DiceCELoss"\
                --optimizer "AdamW"\
                --learning_rate 0.0001\
                --scheduler None\
                --pretrain "yes" --pretrained_model "/mnt/HDD/chest-seg_models/monai_swinunet_v7_240519/model_1100.pt" --error_signal no\
                --wandb "no"\ > monai_swinunet.log 2>&1 &