wandb_version: 1

save_path:
  desc: null
  value: /mnt/HDD/oci-seg_models
version:
  desc: null
  value: v1
cuda:
  desc: null
  value: '0'
num_workers:
  desc: null
  value: 4
wandb:
  desc: null
  value: 'yes '
pretrain:
  desc: null
  value: 'no'
pretrained_model:
  desc: null
  value: .pt
error_signal:
  desc: null
  value: 'no'
ts_batch_size:
  desc: null
  value: 128
vs_batch_size:
  desc: null
  value: 64
learning_rate:
  desc: null
  value: 0.0001
epochs:
  desc: null
  value: 2000
optimizer:
  desc: null
  value: AdamW
scheduler:
  desc: null
  value: None
loss:
  desc: null
  value: DiceCELoss
valid_epoch:
  desc: null
  value: 1
model:
  desc: null
  value: unet
training_date:
  desc: null
  value: '240529'
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.4
    framework: huggingface
    huggingface_version: 4.42.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716981200.0
    t:
      1:
      - 1
      - 2
      - 3
      - 10
      - 11
      - 41
      - 48
      - 49
      - 55
      - 63
      - 71
      - 74
      - 105
      2:
      - 1
      - 2
      - 3
      - 10
      - 11
      - 41
      - 48
      - 49
      - 55
      - 63
      - 71
      - 74
      - 105
      3:
      - 16
      - 17
      - 23
      - 37
      4: 3.8.18
      5: 0.16.4
      6: 4.42.0.dev0
      8:
      - 5
      13: linux-x86_64
